import{a as L,i as b,S as w}from"./assets/vendor-4dYZuk4Q.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q=async(t,r=1)=>{const a="48887234-fe7a8c0ecfa7b9a43b5097f7a",s="https://pixabay.com/api/";try{const e=await L.get(s,{params:{key:a,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}});return{hits:e.data.hits,totalHits:e.data.totalHits}}catch(e){throw console.error("Error fetching data: ",e),e}};function c(t){b.error({title:"Error",message:t})}function v(t){t.innerHTML=""}function S(t){const r=document.createElement("div");return r.classList.add("gallery-item"),r.innerHTML=`
    <a href="${t.largeImageURL}" target="_blank">
      <img src="${t.webformatURL}" alt="${t.tags}" />
    </a>
    <div class="info">
      <p>Likes: ${t.likes}</p>
      <p>Views: ${t.views}</p>
      <p>Comments: ${t.comments}</p>
      <p>Downloads: ${t.downloads}</p>
    </div>
  `,r}function I(t,r){t.forEach(a=>{const s=S(a);r.appendChild(s)})}let d,n=1,y="",f=0;const P=document.querySelector(".search-form"),E=document.querySelector(".search-input"),u=document.querySelector(".gallery"),p=document.querySelector(".loader"),i=document.querySelector(".load-more"),h=document.querySelector(".end-message");function m(){p.style.display="block"}function H(){p.style.display="none"}async function g(t,r){try{const{hits:a,totalHits:s}=await q(t,r);if(a.length===0)c("Sorry, there are no images matching your search query. Please try again!");else{I(a,u);const e=u.querySelector(".gallery-item");if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}d?d.refresh():d=new w(".gallery a",{captionsData:"alt",captionDelay:250}),i.style.display="block"}f=s,n*40>=f&&(i.style.display="none",c("We're sorry, but you've reached the end of search results."),h.style.display="block")}catch{c("Failed to fetch images. Please try again later.")}finally{H()}}P.addEventListener("submit",function(t){t.preventDefault();const r=E.value.trim();if(!r){c("Please enter a search query.");return}y=r,n=1,m(),v(u),h.style.display="none",g(r,n),i.style.display="none"});i.addEventListener("click",function(){n+=1,m(),g(y,n)});
//# sourceMappingURL=index.js.map
